# Generated by Django 5.1.7 on 2025-03-10 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_category_name_en_category_category_name_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'client', 'verbose_name_plural': 'client'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'owner', 'verbose_name_plural': 'owner'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.AddField(
            model_name='carmake',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
