# Generated by Django 5.1.7 on 2025-03-11 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_carreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreview',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_review', to='store.car'),
        ),
    ]
